---

- name: Nginx package is available
  copy:
    src: nginx_1.12.1-1~stretch_amd64.deb
    dest: /root/ansible/packages/nginx_1.12.1-1~stretch_amd64.deb

- name: Nginx is installed
  apt:
    deb: /root/ansible/packages/nginx_1.12.1-1~stretch_amd64.deb
    state: present

- name: Nginx is started and enabled
  service:
    name: nginx
    state: started
    enabled: yes

- name: Nginx default configuration is not available
  file:
    path: "{{item}}"
    state: absent
  with_items:
  - /etc/nginx/conf.d/default.conf
  - /usr/share/nginx/html
  notify: Reload Nginx

- name: Nginx configuration is available
  template:
    src: site.conf
    dest: /etc/nginx/conf.d/site.conf
  notify: Reload Nginx

- block:

  - name: Nginx Grafana password is computed
    command: openssl passwd --salt aA -apr1 {{item|quote}}
    with_items:
    - "{{grafana_admin_password}}"
    - "{{grafana_user_password}}"
    register: htpasswd
    changed_when: false

  - name: Nginx Grafana password is installed
    template:
      src: grafana_htpasswd
      dest: /etc/nginx/grafana_htpasswd
    notify: Reload Nginx

  when: "'monitor' in group_names"

- meta: flush_handlers

- name: Nginx reload is scheduled
  cron:
    name: nginx reload
    minute: 30
    hour: 6,18
    job: /bin/systemctl reload nginx
