---

- hosts: all
  gather_facts: no
  roles:
  - base

- hosts: vagrant
  gather_facts: no
  roles:
  - hosts

- hosts: monitor
  gather_facts: no
  roles:
  - monitor

- hosts: all
  gather_facts: no
  roles:
  - telegraf

- hosts: website
  gather_facts: no
  roles:
  - website
