---

- name: Grafana packages are available
  copy:
    src: "{{item}}"
    dest: /root/ansible/packages/{{item}}
  with_items:
  - grafana_4.4.1_amd64.deb
  - grafana-piechart-panel-11b21df.zip

- name: Grafana is installed
  apt:
    deb: /root/ansible/packages/grafana_4.4.1_amd64.deb
    state: present

- name: Grafana plugins directory exists
  file:
    path: /var/lib/grafana/plugins
    state: directory
    owner: grafana
    group: grafana

- name: Grafana plugins are installed
  unarchive:
    src: /root/ansible/packages/{{item}}
    dest: /var/lib/grafana/plugins
    remote_src: yes
  with_items:
  - grafana-piechart-panel-11b21df.zip
  notify: Reset Grafana

- name: Grafana configuration is installed
  template:
    src: grafana.ini
    dest: /etc/grafana/grafana.ini
  notify: Reset Grafana

- name: Grafana API requests are available
  template:
    src: requests/{{item}}.json
    dest: /root/ansible/requests/grafana-{{item}}.json
    mode: 0600
  with_items:
  - datasource
  - dashboard-host
  - user-organisation
  - user-account
  - user-role
  notify: Reset Grafana

- meta: flush_handlers

- name: Grafana service is started and enabled
  service:
    name: grafana-server
    state: started
    enabled: yes

- name: Grafana is up
  wait_for:
    port: 3000

- name: Grafana datasource, dashboard, and users are configured
  shell: >
    curl
    -X {{item.method}} http://localhost:3000/{{item.endpoint}}
    --user admin:admin
    --header 'Content-Type:application/json'
    --data-binary @/root/ansible/requests/grafana-{{item.name}}.json
    --fail &&
    touch /root/ansible/states/grafana-{{item.name}}.done
  args:
    creates: /root/ansible/states/grafana-{{item.name}}.done
  with_items:
  - name: datasource
    endpoint: api/datasources
    method: POST
  - name: dashboard-host
    endpoint: api/dashboards/db
    method: POST
  - name: user-organisation
    endpoint: api/orgs/1
    method: PUT
  - name: user-account
    endpoint: api/admin/users
    method: POST
  - name: user-role
    endpoint: api/orgs/1/users/2
    method: PATCH
