---

- name: Grafana service is stopped
  service:
    name: grafana-server
    state: stopped

- name: Grafana settings are reset
  file:
    path: /var/lib/grafana/grafana.db
    state: absent

- name: Grafana tasks are reset
  shell: rm -f /root/grafana-tasks/status/*.done
  args:
    warn: no
