---

- name: Package is available
  get_url:
    url: https://dl.influxdata.com/influxdb/releases/influxdb_1.2.4_amd64.deb
    dest: /root/influxdb_1.2.4_amd64.deb
    checksum: sha256:2fac8391e04aa1bec9151e8f0d8f18df030c866af2b4963ab7d86c6ddc172182

- name: Package is installed
  apt:
    deb: /root/influxdb_1.2.4_amd64.deb

- name: Service is started and enabled
  service:
    name: influxdb
    state: started
    enabled: yes

- name: InfluxDB is up
  wait_for:
    port: 8086

- name: Admin user exists
  command: >
    curl -X POST 'http://localhost:8086/query' --data-urlencode "q={{item}}"
  with_items:
  - "CREATE USER {{influxdb_admin_user}} WITH PASSWORD '{{influxdb_admin_password}}' WITH ALL PRIVILEGES"
  args:
    warn: no
  changed_when: false

- name: Configuration is installed
  template:
    src: influxdb.conf
    dest: /etc/influxdb/influxdb.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart InfluxDB

- meta: flush_handlers

- name: InfluxDB is up
  wait_for:
    port: 8086

- name: Telegraf database and user exist
  command: >
    curl -X POST 'http://localhost:8086/query' --data-urlencode "q={{item}}"
    --user {{influxdb_admin_user}}:{{influxdb_admin_password}}
  with_items:
  - "CREATE DATABASE telegraf"
  - "CREATE USER {{influxdb_telegraf_user}} WITH PASSWORD '{{influxdb_telegraf_password}}'"
  - "GRANT WRITE ON telegraf TO {{influxdb_telegraf_user}}"
  args:
    warn: no
  changed_when: false
