---

- name: Package is available
  copy:
    src: influxdb_1.2.4_amd64.deb
    dest: /root/influxdb_1.2.4_amd64.deb
    owner: root
    group: root
    mode: 0644

- name: Package is installed
  apt:
    deb: /root/influxdb_1.2.4_amd64.deb
    state: present

- name: Directory for tasks status exists
  file:
    path: /root/influxdb-tasks
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Service is started and enabled
  service:
    name: influxdb
    state: started
    enabled: yes

- name: InfluxDB is up
  wait_for:
    port: 8086

- name: Admin user exists
  shell: >
    influx
    -execute "{{item.query}}" && touch /root/influxdb-tasks/{{item.name}}.done
  args:
    creates: /root/influxdb-tasks/{{item.name}}.done
  with_items:
  - name: user-admin-create
    query: "CREATE USER {{influxdb_admin_user}} WITH PASSWORD '{{influxdb_admin_password}}' WITH ALL PRIVILEGES"

- name: Configuration is installed
  template:
    src: influxdb.conf
    dest: /etc/influxdb/influxdb.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart InfluxDB

- meta: flush_handlers

- name: InfluxDB is up
  wait_for:
    port: 8086

- name: Telegraf database and users exist
  shell: >
    influx
    -username "{{influxdb_admin_user}}" -password "{{influxdb_admin_password}}"
    -execute "{{item.query}}" && touch /root/influxdb-tasks/{{item.name}}.done
  args:
    creates: /root/influxdb-tasks/{{item.name}}.done
  with_items:
  - name: db-telegraf-create
    query: "CREATE DATABASE telegraf"
  - name: user-telegraf-create
    query: "CREATE USER {{influxdb_telegraf_user}} WITH PASSWORD '{{influxdb_telegraf_password}}'"
  - name: user-telegraf-grant
    query: "GRANT WRITE ON telegraf TO {{influxdb_telegraf_user}}"
  - name: user-grafana-create
    query: "CREATE USER {{influxdb_grafana_user}} WITH PASSWORD '{{influxdb_grafana_password}}'"
  - name: user-grafana-grant
    query: "GRANT READ ON telegraf TO {{influxdb_grafana_user}}"
