---

- name: Package is available
  copy:
    src: grafana_4.4.1_amd64.deb
    dest: /root/grafana_4.4.1_amd64.deb

- name: Package is installed
  apt:
    deb: /root/grafana_4.4.1_amd64.deb
    state: present

- name: Configuration is installed
  template:
    src: grafana.ini
    dest: /etc/grafana/grafana.ini
  notify: Reconfigure Grafana

- name: API calls payload is available
  template:
    src: "{{item}}"
    dest: /root/{{item}}
    mode: 0600
  with_items:
  - datasource.json
  - organisation.json
  - user.json
  - role.json
  notify: Reconfigure Grafana

- meta: flush_handlers

- name: Service is started and enabled
  service:
    name: grafana-server
    state: started
    enabled: yes
