---

- name: Service is stopped
  service:
    name: grafana-server
    state: stopped

- name: Settings are reset
  file:
    path: /var/lib/grafana/grafana.db
    state: absent

- name: Tasks are reset
  shell: rm -f /root/grafana-tasks/status/*.done
  args:
    warn: no
