---

- name: Packages list is up to date
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Packages are installed
  apt:
    name: "{{item}}"
    state: present
  with_items:
  - curl
  - vim

- name: Hostname is set
  hostname:
    name: "{{inventory_hostname}}"
