---

hosts:
  test-01.testdomain:
    box: debian/stretch64
    ip: 192.168.56.101
    memory: 512
  test-02.testdomain:
    box: debian/stretch64
    ip: 192.168.56.102
    memory: 512
  test-03.testdomain:
    box: debian/stretch64
    ip: 192.168.56.103
    memory: 512

groups:
  monitor:
    hosts:
    - test-01.testdomain
    - test-02.testdomain
  website:
    hosts:
    - test-02.testdomain
    - test-03.testdomain
