---

- name: Package is available
  copy:
    src: telegraf_1.3.4-1_amd64.deb
    dest: /root/telegraf_1.3.4-1_amd64.deb
    owner: root
    group: root
    mode: 0644

- name: Package is installed
  apt:
    deb: /root/telegraf_1.3.4-1_amd64.deb

- name: Configuration is installed
  template:
    src: telegraf.conf
    dest: /etc/telegraf/telegraf.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart Telegraf

- meta: flush_handlers

- name: Service is started and enabled
  service:
    name: telegraf
    state: started
    enabled: yes
