---

- include: journal.yml

- name: Apt maintains last update timestamp
  template:
    src: 15update-stamp
    dest: /etc/apt/apt.conf.d/15update-stamp

- name: Packages list is up to date
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Packages are installed
  apt:
    name: "{{item}}"
    state: present
  with_items:
  - curl
  - less
  - vim

- name: Hostname is set
  hostname:
    name: "{{inventory_hostname}}"

- name: Ansible directory structure exists
  file:
    path: "{{item}}"
    state: directory
  with_items:
  - /root/ansible/packages
  - /root/ansible/requests
  - /root/ansible/states
