---

- hosts: localhost
  gather_facts: no

  vars:
    downloads:

    - url: https://github.com/mholt/caddy/releases/download/v0.10.4/caddy_v0.10.4_linux_amd64.tar.gz
      sha256: eaf0be061c4f260eab6b181728457852afc9c53c12c0b6ce9dd130bb4c790917
      dest: playbooks/roles/caddy/files/caddy_v0.10.4_linux_amd64.tar.gz

    - url: https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana_4.4.1_amd64.deb
      sha256: f11ed0ad94a63be108df903ea32a8c2f199bfb87e3c6de26ce3101d3167ed5dd
      dest: playbooks/roles/monitor/files/grafana_4.4.1_amd64.deb

    - url: https://dl.influxdata.com/influxdb/releases/influxdb_1.3.1_amd64.deb
      sha256: 958c95d10b2b9d798003e4231ce3faf389e54fe749b28ef7db86a8058661bef8
      dest: playbooks/roles/monitor/files/influxdb_1.3.1_amd64.deb

    - url: https://dl.influxdata.com/telegraf/releases/telegraf_1.3.4-1_amd64.deb
      sha256: 680375f0138ccbbc5331474ca18ed90e7b8e66177ce46e4978ae955562b4328f
      dest: playbooks/roles/telegraf/files/telegraf_1.3.4-1_amd64.deb

  tasks:

  - name: Packages are available
    command: wget {{item.url}} -O {{item.dest}}
    args:
      creates: "{{item.dest}}"
    with_items: downloads

  - name: Packages integrity is verified
    shell: sha256sum {{item.dest}} | cut -c-64 | grep {{item.sha256}}
    with_items: downloads
    changed_when: false
