---

- hosts: localhost
  gather_facts: no

  vars:
    downloads:

    - url: https://github.com/mholt/caddy/releases/download/v0.10.4/caddy_v0.10.4_linux_amd64.tar.gz
      checksum: sha256:eaf0be061c4f260eab6b181728457852afc9c53c12c0b6ce9dd130bb4c790917
      dest: playbooks/roles/caddy/files/caddy_v0.10.4_linux_amd64.tar.gz

    - url: https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana_4.4.1_amd64.deb
      checksum: sha256:f11ed0ad94a63be108df903ea32a8c2f199bfb87e3c6de26ce3101d3167ed5dd
      dest: playbooks/roles/grafana/files/grafana_4.4.1_amd64.deb

    - url: https://dl.influxdata.com/influxdb/releases/influxdb_1.2.4_amd64.deb
      checksum: sha256:2fac8391e04aa1bec9151e8f0d8f18df030c866af2b4963ab7d86c6ddc172182
      dest: playbooks/roles/influxdb/files/influxdb_1.2.4_amd64.deb

    - url: https://dl.influxdata.com/telegraf/releases/telegraf_1.3.4-1_amd64.deb
      checksum: sha256:680375f0138ccbbc5331474ca18ed90e7b8e66177ce46e4978ae955562b4328f
      dest: playbooks/roles/telegraf/files/telegraf_1.3.4-1_amd64.deb

  tasks:

  - name: Packages are available
    get_url:
      url: "{{item.url}}"
      dest: "{{item.dest}}"
      checksum: "{{item.checksum}}"
      timeout: 3600
    with_items: downloads
