---

- name: Telegraf package is available
  copy:
    src: telegraf_1.3.4-1_amd64.deb
    dest: /root/ansible/packages/telegraf_1.3.4-1_amd64.deb

- name: Telegraf is installed
  apt:
    deb: /root/ansible/packages/telegraf_1.3.4-1_amd64.deb
    state: present

- name: Telegraf configuration is installed
  template:
    src: telegraf.conf
    dest: /etc/telegraf/telegraf.conf
  notify: Restart Telegraf

- meta: flush_handlers

- name: Telegraf service is started and enabled
  service:
    name: telegraf
    state: started
    enabled: yes
